### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by demonlol** [useragents/Snapchat-Snapscore-Botter#24]
Instead of having the end user "not move the window," you could get the window's top left coordinates and calculate the configured offsets.

Even better, if it were possible to "steal" the mouse real quick for botting purposes, get the new delta coordinates from the position _since_ it had been stolen (to halfass compensate for any potential inconvenience to the end user) and teleport it back to the origin + movement

Honestly a vm would suffice for asynchronous use. Imagine 20 instances of BS and an implementation for multi instance support for this on one lol. I figure you'd need to get the BS instance's name/title from the active/foremost window handle while calibrating to provide multi instancing and individual accounts. You could take this a lot farther by making a click script for the BS multi instance manager itself, use ocr to interpret which buttons correspond to which instances, and do something ayysink with that.

oooooh another one: Have the user calibrate the logout/login buttons, and either like a popup window to prompt for the phone/username and password, or some kind of keylogger while end user types it in (would need a way to clear incase they mistype the credentials)

Maybe some kind of "bot schedule" that alternates between bot calibrations/profiles.

If you're up for a challenge, look into using python to inject a frida script into {emulator} through adb which disables sn****at's ssl pinning in order to view the raw requests with a mitm attack and...you know...make an api. It took me a month, coffee coffee coffee, and 1TB worth of google bandwidth to finally work out how I was supposed to debug and look for the right objects, but make sure your script is so to say _forked_ from any of the massive userscripts on frida's website containing practically every ssl pinning method in java (which last time I tried, all were patched to some degree). If you're interested in a headstart, I may still have _everything_ needed to do this with as well as instructions, commands c/p, etc

**Comment by useragents** [comment]
I appreciate your concern and your ideas are good, I have looked into bypassing Snapchat's SSL pinning using Frida with several scripts to bypass and all of the scripts that I tried have been patched, but even then I have heard from friends that the data that Snapchat sends out for even any request is very hard to reverse. Although I haven't looked into Snapchat much at all, I did attempt to reverse their APK but after a few minutes of attempts I gave up since I didn't have the time or effort to continue.

I will keep your ideas into consideration, I appreciate it. I would be interested to look into Snapchat bots and we could work together with your instructions to see if we can make any progress. Thank you
